version: "3.9"
services:
  react:
    build:
      context: ./dockerfiles
      dockerfile: DockerFile
    container_name: react
    volumes:
      - .:/usr/src/app
    ports:
      - "5173:5173"
    networks:
      - laravel_network
    command: npm run dev

networks:
  laravel_network:
    external: true