FROM --platform=arm64 php:8.3-fpm
RUN apt update && \
    apt install -y zlib1g-dev mariadb-client vim libzip-dev && \
    docker-php-ext-install zip pdo_mysql && \
    apt install -y git && \
    pecl install xdebug && \
    docker-php-ext-enable xdebug

COPY ./php.ini /usr/local/etc/php/php.ini 

RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
    php composer-setup.php && \
    php composer-setup.php --install-dir=/usr/local/bin --filename=composer && \
    php -r "unlink('composer-setup.php');"

CMD ["composer install && php artisan migrate --force && "]